#!/usr/bin/env python3

#Chaz Davis
#CIT 144 Spring 2015

#Program I: Temperature Conversion 2/6/2015

#defining variables
temperature1 = 0.0
temperature2 = 0.0
conversion = ""

#retrieving data from user
temperature1 = int(float(input("What temperature would you like to convert")))
conversion = input("Please enter a C to convert to celsius or an F to convert to farenheit")

#Converting with user provided data
if conversion == "C" or conversion == "c":
    temperature2 = float((temperature1 - 32) / 1.8)
    print(temperature1, " degrees Farenheit = %.1f " %temperature2, " degrees Celcius")
elif conversion == "F" or conversion == "f":
    temperature2 = float(temperature1 * 1.8 +32)
    print(temperature1, "degrees Celcius = %.1f " %temperature2, " degrees Farenheit")
else:
    print ("You entered an incorrect value")

